import { BriefcaseBusiness, Droplets, Baby, Crown, Plane, Building2, UserCheck, Sparkles, Battery, Award, HelpCircle, MapPin, Phone, User, X, Copy } from 'lucide-react';

export const whatsappNumber = '77781556699'
export const maxPhoneNumber = '+77055709091'
export const alibekPhoneNumber = '+77781556699'
export const maxPhoneLabel = '+7 705 570 9091 — Максим'
export const alibekPhoneLabel = '+7 778 155 6699 — Алибек'

export const translations = {
  ru: {
    home: 'Главная',
    services: 'Услуги',
    fleet: 'Автопарк',
    standards: 'Стандарты',
    contacts: 'Контакты',
    booking: 'Заказ',
    faqNav: 'FAQ',
    price: 'Прайс',
    history: 'История',
    favorites: 'Избранное',
    saved: '✓ Сохранено',
    menu: 'Меню',
    menuMore: 'Ещё',
    close: 'Закрыть',
    whatsapp: 'WhatsApp',
    continueDraft: 'Продолжить заявку',
    startOrder: 'Начать заказ',
    startOrderAlt: 'Получить цену за 30 секунд',
    draftReminder: 'У вас есть незавершенная заявка',
    continueDraftShort: 'Продолжить',
    installAppTitle: 'Установите приложение MAX',
    installAppHint: 'Открывайте быстрее и заказывайте поездку в два клика.',
    installAppButton: 'Установить',
    installAppLater: 'Позже',
    quickScenarios: 'Быстрые сценарии',
    quickChoice: 'Быстрый выбор',
    reviews: 'Отзывы клиентов',
    noOrders: 'Нет заказов',
    noFavorites: 'Нет избранных адресов',
    clearHistory: 'Очистить',
    clearHistoryFull: 'Очистить историю',
    repeat: 'Повторить',
    hideDetails: 'Скрыть доп. поля',
    showDetails: 'Добавить адрес и комментарий',
    saveAddress: 'Сохранить адрес в избранное',
    submitNow: 'Заказать сейчас',
    fillForm: 'Заполните форму',
    submitWhatsapp: 'Отправить в WhatsApp',
    bookingProgress: 'Прогресс заявки',
    progressStep1: '1. Контакты',
    progressStep2: '2. Услуга и дата',
    progressStep3: '3. Детали (опционально)',
    phoneInvalid: 'Введите корректный номер (+7XXXXXXXXXX)',
    bookingTitle: 'Куда едем?',
    bookingSubtitle: 'Напишите нам прямо сейчас. Обсудим детали, подберем идеальный автомобиль и сразу закрепим за вами водителя.',
    bookingSubtitleShort: 'Оставьте контакты и дату. Подтверждаем быстро в WhatsApp или по звонку.',
    heroBadge: 'MAX · Официальный партнер Яндекс.Такси в Астане',
    heroTitle: 'Таксопарк MAX — сервис, на который можно положиться',
    heroP1: 'Забудьте о стрессе в пути. Мы берем на себя все заботы о ваших поездках: от пунктуальной подачи автомобиля до вашего комфорта в дороге.',
    heroP2: 'Никаких случайных людей за рулем. В нашей команде — аккуратные водители, отлично знающие город и соблюдающие высокий уровень сервиса.',
    heroP3: 'Деловая встреча, трансфер в аэропорт или выезд на природу с семьей — просто сообщите нам маршрут, и мы организуем всё безупречно.',
    partnerDriversTitle: 'Работайте на себя, а рутину оставьте нам',
    partnerDriversSubtitle: 'Надежный официальный партнер с лучшими условиями',
    partnerDriversText: 'Подключаем к Яндекс.Такси за 10 минут. Устали от скрытых комиссий и задержек выплат? В парке MAX всё честно: прозрачный процент, моментальный вывод денег на любую карту (Kaspi/Halyk) и живая поддержка, которая действительно помогает, а не отвечает скриптами.',
    partnerDriversButton: 'Стать партнером',
    driverBadge: 'Водителям Яндекс Такси',
    driverBenefit1Title: 'Справедливая комиссия',
    driverBenefit1Desc: 'Никаких неприятных сюрпризов в конце недели. Вы заранее знаете, сколько отдаете парку — и это самый честный минимум.',
    driverBenefit2Title: 'Вы сами себе босс',
    driverBenefit2Desc: 'Система вас ни в чем не ограничивает. Выходите на линию только тогда, когда это удобно именно вам.',
    driverBenefit3Title: 'Ваши деньги всегда с вами',
    driverBenefit3Desc: 'Выводите заработанное на карты Kaspi или Halyk моментально, хоть каждый день — без выходных и праздников.',
    driverBenefit4Title: 'Своих не бросаем',
    driverBenefit4Desc: 'Мы не просто подключаем к агрегатору, мы защищаем ваши интересы. Спорный заказ или конфликт? Мы всегда на связи и решим вопрос.',
    standardsTitleDesktop: 'Стандарты',
    contactsHint: 'Позвоните или напишите в WhatsApp — мы на связи 24/7',
    nameLabel: 'Ваше имя *',
    phoneLabel: 'Номер телефона *',
    requestTypeLabel: 'Тип заявки *',
    requestTypeOrder: 'Заказ поездки',
    requestTypePartner: 'Стать партнером',
    contactPersonLabel: 'Кому писать *',
    contactPersonMax: 'Максим',
    contactPersonAlibek: 'Алибек',
    serviceLabel: 'Выберите услугу *',
    dateLabel: 'Дата поездки *',
    addressLabel: 'Адрес подачи',
    commentLabel: 'Дополнительные пожелания',
    commentDesktopLabel: 'Комментарий',
    namePlaceholder: 'Например: Дархан',
    phonePlaceholder: '+7 (___) ___-__-__',
    addressPlaceholder: 'Например: Астана, Кабанбай батыра 53',
    commentPlaceholder: 'Поделитесь своими пожеланиями...',
    favoriteAddressPrefix: 'Адрес',
    submitSuccess: 'Заявка открыта в WhatsApp. Мы также сохранили её в истории.',
    removeFavoriteAria: 'Удалить адрес',
    waMessageTitle: 'Заявка MAX Taxi:',
    waName: 'Имя',
    waPhone: 'Телефон',
    waService: 'Услуга',
    waDate: 'Дата',
    waRequestType: 'Тип заявки',
    waContactPerson: 'Контакт',
    waAddress: 'Адрес',
    role: 'Роль',
    roleClient: 'Клиент',
    roleAdmin: 'Администратор',
    roleDriver: 'Водитель',
    adminPanel: 'Панель администратора',
    adminSubtitle: 'Контроль заявок и управление статусами',
    driverPanel: 'Кабинет водителя',
    driverSubtitle: 'Просмотр заказов и отметка этапов поездки',
    orderStatus: 'Статус',
    noOrdersForRole: 'Заказов пока нет',
    orderCreated: 'Создан',
    statusNew: 'Новый',
    statusConfirmed: 'Подтверждён',
    statusOnWay: 'В пути',
    statusCompleted: 'Завершён',
    statusCanceled: 'Отменён',
    setStatus: 'Установить статус',
    ordersTotal: 'Всего заказов',
    ordersActive: 'Активные',
    ordersDone: 'Завершённые',
    loyaltyLevel: 'Уровень клиента',
    loyaltyBronze: 'Bronze',
    loyaltySilver: 'Silver',
    loyaltyGold: 'Gold',
    loyaltyPoints: 'Баллы',
    loyaltyNext: 'До следующего уровня',
    birthdayLabel: 'Дата рождения (опционально)',
    birthdayBonus: 'Бонус ко дню рождения',
    birthdayClaim: 'Получить +50 баллов',
    birthdayClaimed: 'Бонус начислен',
    referralTitle: 'Реферальная программа',
    referralHint: 'Пригласите друга и получите 5% скидку на следующий заказ.',
    referralShare: 'Скопировать текст для WhatsApp',
    referralCopied: 'Текст скопирован',
    monthOrders: 'заказов',
    monthCompleted: 'завершено',
    monthActive: 'активно',
    monthTopService: 'топ услуга',
    priceEstimateLabel: 'Ориентировочная стоимость',
    pricingDetailsToggle: 'Как формируется цена и оплата',
    pricingDetailsHide: 'Скрыть цену и оплату',
    pricingDetailsTitle: 'Прозрачная цена',
    pricingWeekendNote: 'Выходной день: +15% к базовой ставке',
    pricingFinalNote: 'Финальную сумму подтверждает менеджер перед поездкой.',
    paymentMethodsTitle: 'Способы оплаты',
    paymentMethodsList: 'Kaspi, Halyk, наличные, счет для компаний',
    partnerOfferTitle: 'Партнерское предложение',
    partnerOfferOpen: 'Открыть предложение',
    partnerOfferHotelTitle: 'Скидка на отель рядом с аэропортом',
    partnerOfferHotelHint: 'Для маршрутов аэропорт → город доступны спецусловия проживания.',
    partnerOfferFoodTitle: 'Подборка ресторанов в центре',
    partnerOfferFoodHint: 'Если едете в центр, посмотрите лучшие места рядом с точкой прибытия.',
    partnerOfferInsuranceTitle: 'Страховка путешественника',
    partnerOfferInsuranceHint: 'Для дальних поездок рекомендуем оформить короткий страховой полис.',
    summaryTotalSpent: 'Потрачено всего',
    summaryAvgCheck: 'Средний чек',
    summaryFavService: 'Любимая услуга',
    referralAfterOrder: 'Поделитесь реферальным кодом и получите бонус на следующий заказ.',
    analyticsTitle: 'CTA аналитика (локально)',
    analyticsVariant: 'Вариант',
    analyticsOpens: 'Открытия бронирования',
    analyticsSubmits: 'Отправки заявки',
    analyticsConversion: 'Конверсия',
    analyticsReset: 'Сбросить',
    analyticsTopSource: 'Лучший источник',
    analyticsInsufficient: 'Недостаточно данных для вывода',
    funnelTitle: 'Воронка формы (локально)',
    funnelStep1: 'Шаг 1: контакты',
    funnelStep2: 'Шаг 2: услуга и дата',
    funnelStep3: 'Шаг 3: детали',
    funnelSubmit: 'Отправлено',
    funnelConversion: 'Конверсия формы',
    funnelReset: 'Сбросить воронку',
    orderHabitTitle: 'Похоже, у вас есть привычный день заказа',
    orderHabitHint: 'Чаще всего вы заказываете в',
    orderHabitAction: 'Поставить дату',
    orderHabitDismiss: 'Скрыть на 7 дней',
    orderHabitApplied: 'Дата подставлена в форму',
    markConfirmed: 'Подтвердить',
    markOnWay: 'Отметить: в пути',
    markCompleted: 'Отметить: завершён',
    staffLogin: 'Вход для персонала',
    loginLabel: 'Логин',
    passwordLabel: 'Пароль',
    signIn: 'Войти',
    signOut: 'Выйти',
    invalidCredentials: 'Неверный логин или пароль',
    addDriver: 'Добавить водителя',
    driverLogin: 'Логин водителя',
    driverPassword: 'Пароль водителя',
    driversList: 'Список водителей',
    noDrivers: 'Водители пока не добавлены',
    transferSchedule: 'График трансферов',
    transferScheduleSubtitle: 'Назначение водителя и машины с проверкой конфликтов',
    createTransfer: 'Добавить трансфер',
    clientName: 'Клиент',
    routeFrom: 'Откуда',
    routeTo: 'Куда',
    startTime: 'Начало',
    endTime: 'Окончание',
    assignedDriver: 'Водитель',
    vehicle: 'Машина',
    conflictDetected: 'Конфликт: водитель или машина уже заняты в это время',
    invalidTimeRange: 'Время окончания должно быть позже начала',
    transferSaved: 'Трансфер добавлен в график',
    noTransfers: 'Нет запланированных трансферов',
    myTransfers: 'Мои трансферы',
    noTransfersForRole: 'Нет назначенных трансферов',
    filters: 'Фильтры',
    filterDate: 'Дата',
    filterDriver: 'Водитель',
    filterVehicle: 'Машина',
    searchTransfers: 'Поиск по клиенту/маршруту',
    clearFilters: 'Сбросить фильтры',
    bufferLabel: 'Буфер (мин) к проверке конфликтов',
    bufferHelper: 'Добавляет запас ко времени начала/конца для водителя и машины',
    exportJson: 'Экспорт JSON',
    importJson: 'Импорт JSON',
    printSchedule: 'Печать / PDF',
    importSuccess: 'Импорт выполнен',
    importError: 'Ошибка импорта: неверный файл',
    notifyLabel: 'Уведомления о заявке',
    notifyEnable: 'Включите браузерные уведомления, чтобы не пропустить ответ менеджера',
    notifyEnabled: 'Уведомления включены',
    notifyBlocked: 'Браузер отклонил уведомления. Проверьте настройки',
    notifyButton: 'Включить уведомления',
    notifyTitle: 'Заявка отправлена',
    notifyBody: 'Мы свяжемся с вами для подтверждения бронирования',
    supportCardTitle: 'Связаться с менеджером',
    supportCall: 'Позвонить',
    supportEmail: 'Написать на почту',
    supportWhatsapp: 'Открыть WhatsApp',
    preferredContactTitle: 'Предпочитаемый канал',
    preferCall: 'Звонок',
    preferWhatsapp: 'WhatsApp',
    primaryCtaCall: 'Позвонить сейчас',
    receiptEmailButton: 'Квитанция на email',
    receiptPdfButton: 'Скачать PDF',
    receiptPrompt: 'Введите email для квитанции',
    receiptInvalid: 'Введите корректный email адрес',
    receiptOpened: 'Черновик письма с квитанцией открыт',
    receiptPdfReady: 'PDF-квитанция скачивается',
    receiptPdfFailed: 'Не удалось сформировать PDF-квитанцию',
    lastOrderTitle: 'Последняя заявка',
    lastOrderEmpty: 'У вас пока нет заявок',
    statusTimeline: 'Этапы',
    staffLoginPlaceholder: 'admin или driver@mail.ru',
    staffLoginHint: 'Вход персонала доступен только в защищённом backend-контуре.',
    transferSearchPlaceholder: 'Имя, адрес, маршрут',
    clientNamePlaceholder: 'Имя клиента',
    routeFromPlaceholder: 'Астана, аэропорт',
    routeToPlaceholder: 'Отель',
    driverLoginPlaceholder: 'driver@mail.ru',
    vehiclePlaceholder: 'Mercedes V-class',
    detectLocation: 'Определить мое место',
    locating: 'Определяем место...',
    locationSuccess: 'Адрес подставлен в форму',
    locationDenied: 'Доступ к геолокации запрещен',
    locationUnavailable: 'Геолокация недоступна в этом браузере',
    locationFailed: 'Не удалось определить адрес, проверьте интернет или разрешение',
    voiceInputAddress: 'Сказать адрес',
    voiceInputListening: 'Слушаем...',
    voiceInputUnsupported: 'Голосовой ввод недоступен в этом браузере',
    voiceInputNoSpeech: 'Речь не распознана, попробуйте еще раз',
    voiceInputApplied: 'Адрес добавлен голосом',
    trustNoHiddenFees: 'Без скрытых доплат',
    trustNda: 'Конфиденциальность поездок и маршрутов',
    trustInsured: 'Страхование пассажиров и ответственности',
    privacyConsentLabel: 'Я согласен(а) на обработку персональных данных для оформления заявки',
    privacyPolicyLabel: 'Политика конфиденциальности',
    termsLabel: 'Условия обслуживания',
    rememberDataLabel: 'Запомнить данные на этом устройстве',
    rememberDataHint: 'Если отключено, данные сохраняются только в текущей сессии браузера',
    clearMyData: 'Удалить мои данные с устройства',
    dataCleared: 'Локальные данные удалены',
    submitConsentRequired: 'Подтвердите согласие на обработку данных',
    waIncludeSensitive: 'Добавить адрес и комментарий в WhatsApp',
    waPrivacyHint: 'В WhatsApp отправляются только базовые данные. Адрес и комментарий добавляются только по вашему выбору.',
    staffLoginDisabled: 'Вход для персонала доступен только в защищенном контуре (backend). Демо-вход отключен.',
    waComment: 'Комментарий',
    legalDisclaimer: 'Работаем по договору и соблюдаем политику конфиденциальности.',
    priceFromTrip: 'от 10 000 ₸ за поездку',
    moreItems: 'ещё',
    callAriaLabel: 'Позвонить',
    bottomBrand: 'MAX · Таксопарк',
    orderNowCta: 'Заказать сейчас ->',
    offlineDemo: 'Оффлайн демо',
    deleteTransferAria: 'Удалить трансфер',
    footerTagline: 'Таксопарк MAX в Астане: такси и трансферы',
    favNoteEdit: 'Заметка',
    favNotePlaceholder: 'Например: паркинг слева',
    reactivationTitle: 'Давно не заказывали?',
    reactivationHint: 'Вернитесь и получите скидку 5% на следующую поездку — введите промокод',
    reactivationCode: 'WELCOME5',
    reactivationDismiss: 'Не сейчас',
    reactivationOrder: 'Заказать со скидкой',
    historyAutoCleanedNotice: 'Старые заказы (>90 дней) автоматически удалены для вашей конфиденциальности.',
    fleetTitle: 'Наш автопарк',
    corporateTitle: 'MAX для бизнеса',
    corpSubtitle: 'Корпоративное такси и трансферы',
    corpP1: 'Избавьтесь от головной боли с логистикой команды. Мы берем на себя развозку ваших сотрудников, встречу VIP-гостей и поездки руководителей. Предоставляем индивидуального менеджера, безупречные автомобили и полную прозрачность в закрывающих документах (ЭСФ).',
    corpBen1: 'Официальный договор и ЭСФ',
    corpBen2: 'Личный менеджер 24/7',
    corpBen3: 'Удобная оплата в конце месяца',
    faqTitle: 'Частые вопросы',
  },
  kk: {
    home: 'Басты бет',
    services: 'Қызметтер',
    standards: 'Стандарттар',
    contacts: 'Байланыс',
    booking: 'Тапсырыс',
    price: 'Баға',
    history: 'Тарих',
    favorites: 'Таңдаулылар',
    saved: '✓ Сақталды',
    menu: 'Мәзір',
    menuMore: 'Қосымша',
    close: 'Жабу',
    whatsapp: 'WhatsApp',
    continueDraft: 'Өтінімді жалғастыру',
    startOrder: 'Тапсырысты бастау',
    startOrderAlt: '30 секундта баға алу',
    draftReminder: 'Сізде аяқталмаған өтінім бар',
    continueDraftShort: 'Жалғастыру',
    installAppTitle: 'MAX қолданбасын орнатыңыз',
    installAppHint: 'Тезірек ашыңыз және поездкаңызды екі рет басумен ұйымдастырыңыз.',
    installAppButton: 'Орнату',
    installAppLater: 'Кейінірек',
    quickScenarios: 'Жылдам сценарийлер',
    quickChoice: 'Жылдам таңдау',
    reviews: 'Клиент пікірлері',
    noOrders: 'Тапсырыстар жоқ',
    noFavorites: 'Таңдаулы мекенжайлар жоқ',
    clearHistory: 'Тазарту',
    clearHistoryFull: 'Тарихты тазарту',
    repeat: 'Қайта тапсыру',
    hideDetails: 'Қосымша өрістерді жасыру',
    showDetails: 'Мекенжай мен пікір қосу',
    saveAddress: 'Мекенжайды таңдаулыға сақтау',
    submitNow: 'Қазір тапсырыс беру',
    fillForm: 'Форманы толтырыңыз',
    submitWhatsapp: 'WhatsApp-қа жіберу',
    bookingProgress: 'Өтінім прогресі',
    progressStep1: '1. Байланыс',
    progressStep2: '2. Қызмет және күн',
    progressStep3: '3. Детальдар (міндетті емес)',
    phoneInvalid: 'Дұрыс нөмір енгізіңіз (+7XXXXXXXXXX)',
    bookingTitle: 'Ыңғайлы сапарға дайынсыз ба?',
    bookingSubtitle: 'Астана ішінде такси, әуежайға трансфер немесе корпоративтік сапарға тапсырыс беріңіз — біз 24/7 байланыстамыз.',
    bookingSubtitleShort: 'Байланыс пен күнді енгізіңіз. WhatsApp не қоңырау арқылы жылдам растаймыз.',
    heroBadge: 'Астана · MAX таксопаркі · Яндекс Такси серіктесі',
    heroTitle: 'MAX таксопаркі — Астанадағы және қала сыртындағы ыңғайлы сапарлар',
    heroP1: 'Біз такси, трансфер және корпоративтік сапарлардың қызметтерін қауіпсіздік, комфорт және маршрут дәлдігіне баса жүргіземіз.',
    heroP2: 'MAX — Астанада және оның айналасында сапарларыңызды ұсынуға дайын қазіргі заманғы таксопарк.',
    heroP3: 'Сізге қала ішіндегі рейс, әуежайға сапар немесе жеке трансфер қажет болса — біз ыңғайлы нұсқаны ұсынамыз.',
    partnerDriversTitle: 'MAX паркі арқылы Яндекс Таксиге қосылыңыз',
    partnerDriversSubtitle: 'Ең жақсы шарттары бар сенімді ресми серіктес',
    partnerDriversText: 'Яндекс Таксиде жұмыс істеу үшін адал таксопарк іздеп жүрсіз бе? Біз төмен комиссия, қолдау және лездік төлемдерді ұсынамыз. Өз көліктері бар жүргізушілерді 10 минутта қосамыз.',
    partnerDriversButton: 'Серіктес болу',
    driverBadge: 'Яндекс Такси жүргізушілеріне',
    driverBenefit1Title: 'Парктің төмен комиссиясы',
    driverBenefit1Desc: 'Мөлдір есеп айырысулар және жасырын төлемдер жоқ. Әр тапсырыстан ең төменгі пайызды бересіз.',
    driverBenefit2Title: 'Еркін кесте',
    driverBenefit2Desc: 'Өзіңізге ыңғайлы уақытта жұмыс істеңіз. Яндекс GO желісінде қанша уақыт өткізетініңізді өзіңіз шешесіз.',
    driverBenefit3Title: 'Лездік төлемдер 24/7',
    driverBenefit3Desc: 'Тапқан ақшаңызды кез келген күні, тәуліктің кез келген уақытында Kaspi немесе Halyk карталарына шығарыңыз.',
    driverBenefit4Title: 'Желідегі қолдау',
    driverBenefit4Desc: 'Ресми сертификатталған серіктес. Клиенттер мен тапсырыстар бойынша кез келген сұрақтарды шешуге әрқашан дайынбыз.',
    standardsTitleDesktop: 'Стандарттар',
    contactsHint: 'Қоңырау шалыңыз немесе WhatsApp-қа жазыңыз — біз 24/7 байланыстамыз',
    nameLabel: 'Атыңыз *',
    phoneLabel: 'Телефон нөмірі *',
    requestTypeLabel: 'Өтінім түрі *',
    requestTypeOrder: 'Сапарды брондау',
    requestTypePartner: 'Партнер болу',
    contactPersonLabel: 'Кімге жазу *',
    contactPersonMax: 'Максим',
    contactPersonAlibek: 'Әлібек',
    serviceLabel: 'Қызметті таңдаңыз *',
    dateLabel: 'Сапар күні *',
    addressLabel: 'Жіберу мекенжайы',
    commentLabel: 'Қосымша тілектер',
    commentDesktopLabel: 'Пікір',
    namePlaceholder: 'Мысалы: Дархан',
    phonePlaceholder: '+7 (___) ___-__-__',
    addressPlaceholder: 'Мысалы: Астана, Қабанбай батыр 53',
    commentPlaceholder: 'Тілектеріңізді жазыңыз...',
    favoriteAddressPrefix: 'Мекенжай',
    submitSuccess: 'Өтінім WhatsApp-та ашылды. Сондай-ақ, тарихта сақталды.',
    removeFavoriteAria: 'Мекенжайды жою',
    waMessageTitle: 'MAX Taxi өтінімі:',
    waName: 'Аты',
    waPhone: 'Телефон',
    waService: 'Қызмет',
    waDate: 'Күні',
    waAddress: 'Мекенжай',
    role: 'Рөл',
    roleClient: 'Клиент',
    roleAdmin: 'Әкімші',
    roleDriver: 'Жүргізуші',
    adminPanel: 'Әкімші панелі',
    adminSubtitle: 'Өтінімдерді бақылау және мәртебені басқару',
    driverPanel: 'Жүргізуші кабинеті',
    driverSubtitle: 'Тапсырыстарды көру және сапар кезеңдерін белгілеу',
    orderStatus: 'Мәртебе',
    noOrdersForRole: 'Тапсырыстар әлі жоқ',
    orderCreated: 'Құрылған',
    statusNew: 'Жаңа',
    statusConfirmed: 'Расталған',
    statusOnWay: 'Жолда',
    statusCompleted: 'Аяқталды',
    statusCanceled: 'Бас тартылды',
    setStatus: 'Мәртебені орнату',
    ordersTotal: 'Барлық тапсырыс',
    ordersActive: 'Белсенді',
    ordersDone: 'Аяқталған',
    loyaltyLevel: 'Клиент деңгейі',
    loyaltyBronze: 'Bronze',
    loyaltySilver: 'Silver',
    loyaltyGold: 'Gold',
    loyaltyPoints: 'Ұпайлар',
    loyaltyNext: 'Келесі деңгейге дейін',
    birthdayLabel: 'Туған күн (міндетті емес)',
    birthdayBonus: 'Туған күн бонусы',
    birthdayClaim: '+50 ұпай алу',
    birthdayClaimed: 'Бонус қосылды',
    referralTitle: 'Реферал бағдарлама',
    referralHint: 'Досыңызды шақырып, келесі тапсырысқа 5% жеңілдік алыңыз.',
    referralShare: 'WhatsApp мәтінін көшіру',
    referralCopied: 'Мәтін көшірілді',
    monthOrders: 'тапсырыс',
    monthCompleted: 'аяқталған',
    monthActive: 'белсенді',
    monthTopService: 'топ қызмет',
    priceEstimateLabel: 'Шамаланған құны',
    pricingDetailsToggle: 'Баға мен төлем қалай есептеледі',
    pricingDetailsHide: 'Баға мен төлемді жасыру',
    pricingDetailsTitle: 'Ашық баға',
    pricingWeekendNote: 'Демалыс күні: базалық тарифке +15%',
    pricingFinalNote: 'Соңғы соманы сапар алдында менеджер растайды.',
    paymentMethodsTitle: 'Төлем тәсілдері',
    paymentMethodsList: 'Kaspi, Halyk, қолма-қол, компанияларға шот',
    partnerOfferTitle: 'Серіктестік ұсыныс',
    partnerOfferOpen: 'Ұсынысты ашу',
    partnerOfferHotelTitle: 'Әуежай маңындағы қонақүйге жеңілдік',
    partnerOfferHotelHint: 'Әуежай → қала бағыттарына арнайы тұру шарттары қолжетімді.',
    partnerOfferFoodTitle: 'Орталықтағы мейрамханалар топтамасы',
    partnerOfferFoodHint: 'Орталыққа бара жатсаңыз, келу нүктесі маңындағы үздік орындарды қараңыз.',
    partnerOfferInsuranceTitle: 'Саяхат сақтандыруы',
    partnerOfferInsuranceHint: 'Ұзақ сапарлар үшін қысқа сақтандыру полисін ұсынамыз.',
    summaryTotalSpent: 'Жалпы шығын',
    summaryAvgCheck: 'Орташа чек',
    summaryFavService: 'Таңдаулы қызмет',
    referralAfterOrder: 'Реферал кодын бөлісіп, келесі тапсырысқа бонус алыңыз.',
    analyticsTitle: 'CTA аналитикасы (локалды)',
    analyticsVariant: 'Нұсқа',
    analyticsOpens: 'Брондау ашылуы',
    analyticsSubmits: 'Өтінім жіберілді',
    analyticsConversion: 'Конверсия',
    analyticsReset: 'Тазалау',
    analyticsTopSource: 'Ең тиімді арна',
    analyticsInsufficient: 'Қорытындыға дерек аз',
    funnelTitle: 'Форма воронкасы (локалды)',
    funnelStep1: '1-қадам: байланыс',
    funnelStep2: '2-қадам: қызмет және күн',
    funnelStep3: '3-қадам: детальдар',
    funnelSubmit: 'Жіберілді',
    funnelConversion: 'Форма конверсиясы',
    funnelReset: 'Воронканы тазалау',
    orderHabitTitle: 'Сізде тұрақты тапсырыс күні бар сияқты',
    orderHabitHint: 'Сіз көбіне мына күні тапсырыс бересіз:',
    orderHabitAction: 'Күнді қою',
    orderHabitDismiss: '7 күнге жасыру',
    orderHabitApplied: 'Күн формаға қойылды',
    markConfirmed: 'Растау',
    markOnWay: 'Белгілеу: жолда',
    markCompleted: 'Белгілеу: аяқталды',
    staffLogin: 'Персоналға кіру',
    loginLabel: 'Логин',
    passwordLabel: 'Құпиясөз',
    signIn: 'Кіру',
    signOut: 'Шығу',
    invalidCredentials: 'Логин немесе құпиясөз қате',
    addDriver: 'Жүргізуші қосу',
    driverLogin: 'Жүргізуші логині',
    driverPassword: 'Жүргізуші құпиясөзі',
    driversList: 'Жүргізушілер тізімі',
    noDrivers: 'Жүргізушілер әлі қосылмаған',
    transferSchedule: 'Трансфер кестесі',
    transferScheduleSubtitle: 'Жүргізуші мен көлікті тағайындау, қақтығысты тексеру',
    createTransfer: 'Трансфер қосу',
    clientName: 'Клиент',
    routeFrom: 'Қайдан',
    routeTo: 'Қайда',
    startTime: 'Басталуы',
    endTime: 'Аяқталуы',
    assignedDriver: 'Жүргізуші',
    vehicle: 'Көлік',
    conflictDetected: 'Қақтығыс: жүргізуші немесе көлік осы уақытта бос емес',
    invalidTimeRange: 'Аяқталу уақыты басталу уақытынан кейін болуы керек',
    transferSaved: 'Трансфер кестеге қосылды',
    noTransfers: 'Жоспарланған трансфер жоқ',
    myTransfers: 'Менің трансферлерім',
    noTransfersForRole: 'Сізге тағайындалған трансфер жоқ',
    filters: 'Сүзгілер',
    filterDate: 'Күні',
    filterDriver: 'Жүргізуші',
    filterVehicle: 'Көлік',
    searchTransfers: 'Клиент/маршрут бойынша іздеу',
    clearFilters: 'Сүзгілерді тазарту',
    bufferLabel: 'Қақтығысқа буфер (мин)',
    bufferHelper: 'Жүргізуші/көлік уақытына запас қосады',
    exportJson: 'JSON экспорт',
    importJson: 'JSON импорт',
    printSchedule: 'Басып шығару / PDF',
    importSuccess: 'Импорт орындалды',
    importError: 'Импорт қатесі: файл дұрыс емес',
    notifyLabel: 'Өтінім хабарламалары',
    notifyEnable: 'Менеджер жауаптарын жіберіп алмау үшін браузер хабарламаларын қосыңыз',
    notifyEnabled: 'Хабарламалар қосылған',
    notifyBlocked: 'Браузер хабарламаны бұғаттады. Баптауды тексеріңіз',
    notifyButton: 'Хабарламаларды қосу',
    notifyTitle: 'Өтінім жіберілді',
    notifyBody: 'Брондауды растау үшін хабарласамыз',
    supportCardTitle: 'Менеджермен байланыс',
    supportCall: 'Қоңырау шалу',
    supportEmail: 'Поштаға жазу',
    supportWhatsapp: 'WhatsApp ашу',
    preferredContactTitle: 'Қалаулы байланыс арнасы',
    preferCall: 'Қоңырау',
    preferWhatsapp: 'WhatsApp',
    primaryCtaCall: 'Қазір қоңырау шалу',
    receiptEmailButton: 'Квитанцияны email-ға',
    receiptPdfButton: 'PDF жүктеу',
    receiptPrompt: 'Квитанция үшін email енгізіңіз',
    receiptInvalid: 'Дұрыс email мекенжайын енгізіңіз',
    receiptOpened: 'Квитанция бар хат жобасы ашылды',
    receiptPdfReady: 'PDF-квитанция жүктеліп жатыр',
    receiptPdfFailed: 'PDF-квитанцияны жасау мүмкін болмады',
    lastOrderTitle: 'Соңғы өтінім',
    lastOrderEmpty: 'Өтінімдер әлі жоқ',
    statusTimeline: 'Кезеңдер',
    staffLoginPlaceholder: 'admin немесе driver@mail.ru',
    staffLoginHint: 'Персоналға кіру тек қорғалған backend контурында қолжетімді.',
    transferSearchPlaceholder: 'Аты, мекенжайы, маршрут',
    clientNamePlaceholder: 'Клиент аты',
    routeFromPlaceholder: 'Астана, әуежай',
    routeToPlaceholder: 'Қонақ үй',
    driverLoginPlaceholder: 'driver@mail.ru',
    vehiclePlaceholder: 'Mercedes V-class',
    detectLocation: 'Менің орнымды анықтау',
    locating: 'Орын анықталып жатыр...',
    locationSuccess: 'Мекенжай формаға қойылды',
    locationDenied: 'Геолокацияға рұқсат берілмеді',
    locationUnavailable: 'Бұл браузерде геолокация қолжетімсіз',
    locationFailed: 'Мекенжайды анықтау мүмкін болмады, интернет пен рұқсатты тексеріңіз',
    voiceInputAddress: 'Мекенжайды айту',
    voiceInputListening: 'Тыңдап тұрмыз...',
    voiceInputUnsupported: 'Дауыспен енгізу бұл браузерде қолжетімсіз',
    voiceInputNoSpeech: 'Сөйлеу танылмады, қайта көріңіз',
    voiceInputApplied: 'Мекенжай дауыспен қосылды',
    trustNoHiddenFees: 'Жасырын төлемдер жоқ',
    trustNda: 'Сапар мен маршрут құпиялығы',
    trustInsured: 'Жолаушы және жауапкершілік сақтандырылған',
    privacyConsentLabel: 'Өтінімді рәсімдеу үшін дербес деректерді өңдеуге келісемін',
    privacyPolicyLabel: 'Құпиялылық саясаты',
    termsLabel: 'Қызмет көрсету шарттары',
    rememberDataLabel: 'Осы құрылғыда деректерді сақтау',
    rememberDataHint: 'Өшірілсе, деректер тек ағымдағы браузер сессиясында сақталады',
    clearMyData: 'Құрылғыдан менің деректерімді өшіру',
    dataCleared: 'Жергілікті деректер өшірілді',
    submitConsentRequired: 'Деректерді өңдеуге келісімді растаңыз',
    waIncludeSensitive: 'WhatsApp-қа мекенжай мен пікірді қосу',
    waPrivacyHint: 'WhatsApp-қа тек негізгі деректер жіберіледі. Мекенжай мен пікір тек сіз таңдасаңыз қосылады.',
    staffLoginDisabled: 'Персоналға кіру тек қорғалған контурда (backend) қолжетімді. Демо-кіру өшірілген.',
    waComment: 'Пікір',
    legalDisclaimer: 'Келісімшартпен жұмыс істейміз және құпиялылық саясатын сақтаймыз.',
    priceFromTrip: 'сапарға 10 000 ₸ бастап',
    moreItems: 'тағы',
    callAriaLabel: 'Қоңырау шалу',
    bottomBrand: 'MAX · Таксопарк',
    orderNowCta: 'Қазір тапсырыс беру ->',
    offlineDemo: 'Офлайн демо',
    deleteTransferAria: 'Трансферді жою',
    footerTagline: 'Астанадағы MAX таксопаркі: такси және трансферлер',
    favNotePlaceholder: 'Мысалы: сол жақта тұрақ',
    reactivationTitle: 'Дұрыс тапсырыс етпедіңіз бе?',
    reactivationHint: 'Оралыңыз және келіңіз — промокодпен 5% жеңілдік алыңыз',
    reactivationCode: 'WELCOME5',
    reactivationDismiss: 'Қазір емес',
    reactivationOrder: 'Жеңілікпен тапсырис беру',
    historyAutoCleanedNotice: 'Ескі тапсырыстар (>90 күн) конфиденциалдылық ушін автоматты жойылды.',
    fleetTitle: 'Біздің автопарк',
    corporateTitle: 'Бизнес үшін MAX',
    corpSubtitle: 'Корпоративтік клиенттерге қызмет көрсету',
    corpP1: 'Компанияларға мамандандырылған қызмет көрсетеміз. Жеке менеджер, айлық есеп және барлық құжаттар.',
    corpBen1: 'ҚҚС бар ЭШФ',
    corpBen2: 'Жеке менеджер 24/7',
    corpBen3: 'Кейін төлеу (Post-payment)',
    faqTitle: 'Жиі қойылатын сұрақтар',
  },
  en: {
    home: 'Home',
    services: 'Services',
    fleet: 'Fleet',
    standards: 'Standards',
    contacts: 'Contacts',
    booking: 'Booking',
    faqNav: 'FAQ',
    price: 'Pricing',
    history: 'History',
    favorites: 'Favorites',
    saved: '✓ Saved',
    menu: 'Menu',
    menuMore: 'More',
    close: 'Close',
    whatsapp: 'WhatsApp',
    continueDraft: 'Continue request',
    startOrder: 'Start booking',
    startOrderAlt: 'Get price in 30 seconds',
    draftReminder: 'You have an unfinished booking',
    continueDraftShort: 'Continue',
    installAppTitle: 'Install MAX app',
    installAppHint: 'Open faster and book your trip in a couple of taps.',
    installAppButton: 'Install',
    installAppLater: 'Later',
    quickScenarios: 'Quick scenarios',
    quickChoice: 'Quick choice',
    reviews: 'Client reviews',
    noOrders: 'No orders yet',
    noFavorites: 'No favorite addresses',
    clearHistory: 'Clear',
    clearHistoryFull: 'Clear history',
    repeat: 'Repeat',
    hideDetails: 'Hide optional fields',
    showDetails: 'Add address and comment',
    saveAddress: 'Save address to favorites',
    submitNow: 'Book now',
    fillForm: 'Fill required fields',
    submitWhatsapp: 'Send to WhatsApp',
    bookingProgress: 'Booking progress',
    progressStep1: '1. Contacts',
    progressStep2: '2. Service and date',
    progressStep3: '3. Details (optional)',
    phoneInvalid: 'Enter a valid number (+7XXXXXXXXXX)',
    bookingTitle: 'Ready for a comfortable ride?',
    bookingSubtitle: 'Book city taxi, airport transfer, or a corporate ride — our team is available 24/7.',
    bookingSubtitleShort: 'Leave contact details and date. We confirm quickly via WhatsApp or phone.',
    heroBadge: 'Astana · MAX taxi park · Yandex Taxi partner',
    heroTitle: 'MAX taxi park — comfortable rides across Astana and beyond',
    heroP1: 'We provide taxi, transfer, and corporate travel services with a focus on safety, comfort, and route precision.',
    heroP2: 'MAX is a modern taxi park with drivers ready to handle your trips in Astana and beyond.',
    heroP3: 'Whether you need a city ride, airport transfer, or a personalised transfer — we will find the right option.',
    partnerDriversTitle: 'Connect to Yandex Taxi through MAX park',
    partnerDriversSubtitle: 'Reliable official partner with the best conditions',
    partnerDriversText: 'Looking for a fair taxi park to work in Yandex Taxi? We offer low commission, support, and instant payouts. Connect with your personal vehicle in 10 minutes.',
    partnerDriversButton: 'Become a partner',
    driverBadge: 'For Yandex Taxi drivers',
    driverBenefit1Title: 'Low park commission',
    driverBenefit1Desc: 'Transparent settlements and no hidden fees. You pay the minimum percentage from each order.',
    driverBenefit2Title: 'Flexible schedule',
    driverBenefit2Desc: 'Work whenever it suits you. You decide how much time to spend on the Yandex GO line.',
    driverBenefit3Title: 'Instant payouts 24/7',
    driverBenefit3Desc: 'Withdraw your earnings to Kaspi or Halyk cards on any day, at any time of the day.',
    driverBenefit4Title: 'Support on the line',
    driverBenefit4Desc: 'Official certified partner. Always in touch to resolve any client and order issues.',
    standardsTitleDesktop: 'Standard of Excellence',
    contactsHint: 'Call or message us on WhatsApp — available 24/7',
    nameLabel: 'Your name *',
    phoneLabel: 'Phone number *',
    requestTypeLabel: 'Request type *',
    requestTypeOrder: 'Book a ride',
    requestTypePartner: 'Become a partner',
    contactPersonLabel: 'Contact person *',
    contactPersonMax: 'Maxim',
    contactPersonAlibek: 'Alibek',
    serviceLabel: 'Choose service *',
    dateLabel: 'Trip date *',
    addressLabel: 'Pickup address',
    commentLabel: 'Additional notes',
    commentDesktopLabel: 'Comment',
    namePlaceholder: 'Example: Darkhan',
    phonePlaceholder: '+7 (___) ___-__-__',
    addressPlaceholder: 'Example: Astana, Kabanbay Batyr 53',
    commentPlaceholder: 'Share your preferences...',
    favoriteAddressPrefix: 'Address',
    submitSuccess: 'Request opened in WhatsApp and saved to history.',
    removeFavoriteAria: 'Remove address',
    waMessageTitle: 'MAX Taxi request:',
    waName: 'Name',
    waPhone: 'Phone',
    waService: 'Service',
    waDate: 'Date',
    waRequestType: 'Request type',
    waContactPerson: 'Contact',
    waAddress: 'Address',
    role: 'Role',
    roleClient: 'Client',
    roleAdmin: 'Administrator',
    roleDriver: 'Driver',
    adminPanel: 'Administrator panel',
    adminSubtitle: 'Order control and status management',
    driverPanel: 'Driver workspace',
    driverSubtitle: 'View orders and mark trip status',
    orderStatus: 'Status',
    noOrdersForRole: 'No orders yet',
    orderCreated: 'Created',
    statusNew: 'New',
    statusConfirmed: 'Confirmed',
    statusOnWay: 'On the way',
    statusCompleted: 'Completed',
    statusCanceled: 'Canceled',
    setStatus: 'Set status',
    ordersTotal: 'Total orders',
    ordersActive: 'Active',
    ordersDone: 'Completed',
    loyaltyLevel: 'Client level',
    loyaltyBronze: 'Bronze',
    loyaltySilver: 'Silver',
    loyaltyGold: 'Gold',
    loyaltyPoints: 'Points',
    loyaltyNext: 'To next level',
    birthdayLabel: 'Birthday (optional)',
    birthdayBonus: 'Birthday bonus',
    birthdayClaim: 'Claim +50 points',
    birthdayClaimed: 'Bonus claimed',
    referralTitle: 'Referral program',
    referralHint: 'Invite a friend and get 5% off your next booking.',
    referralShare: 'Copy WhatsApp text',
    referralCopied: 'Text copied',
    monthOrders: 'orders',
    monthCompleted: 'completed',
    monthActive: 'active',
    monthTopService: 'top service',
    priceEstimateLabel: 'Estimated price',
    pricingDetailsToggle: 'How pricing and payment work',
    pricingDetailsHide: 'Hide pricing and payment',
    pricingDetailsTitle: 'Transparent pricing',
    pricingWeekendNote: 'Weekend day: +15% to the base rate',
    pricingFinalNote: 'Final amount is confirmed by the manager before the trip.',
    paymentMethodsTitle: 'Payment methods',
    paymentMethodsList: 'Kaspi, Halyk, cash, invoice for companies',
    partnerOfferTitle: 'Partner offer',
    partnerOfferOpen: 'Open offer',
    partnerOfferHotelTitle: 'Hotel discount near the airport',
    partnerOfferHotelHint: 'Special accommodation terms are available for airport-to-city routes.',
    partnerOfferFoodTitle: 'Best restaurants in the city center',
    partnerOfferFoodHint: 'If you are going downtown, check top places near your arrival point.',
    partnerOfferInsuranceTitle: 'Travel insurance option',
    partnerOfferInsuranceHint: 'For longer trips we recommend a short-term travel policy.',
    summaryTotalSpent: 'Total spent',
    summaryAvgCheck: 'Average check',
    summaryFavService: 'Favorite service',
    referralAfterOrder: 'Share your referral code and get a bonus on your next booking.',
    analyticsTitle: 'CTA analytics (local)',
    analyticsVariant: 'Variant',
    analyticsOpens: 'Booking opens',
    analyticsSubmits: 'Submitted orders',
    analyticsConversion: 'Conversion',
    analyticsReset: 'Reset',
    analyticsTopSource: 'Top source',
    analyticsInsufficient: 'Not enough data yet',
    funnelTitle: 'Form funnel (local)',
    funnelStep1: 'Step 1: contacts',
    funnelStep2: 'Step 2: service and date',
    funnelStep3: 'Step 3: details',
    funnelSubmit: 'Submitted',
    funnelConversion: 'Form conversion',
    funnelReset: 'Reset funnel',
    orderHabitTitle: 'You seem to have a usual booking day',
    orderHabitHint: 'You most often book on',
    orderHabitAction: 'Set date',
    orderHabitDismiss: 'Hide for 7 days',
    orderHabitApplied: 'Date has been set in the form',
    markConfirmed: 'Confirm',
    markOnWay: 'Mark: on the way',
    markCompleted: 'Mark: completed',
    staffLogin: 'Staff login',
    loginLabel: 'Login',
    passwordLabel: 'Password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    invalidCredentials: 'Invalid login or password',
    addDriver: 'Add driver',
    driverLogin: 'Driver login',
    driverPassword: 'Driver password',
    driversList: 'Drivers list',
    noDrivers: 'No drivers added yet',
    transferSchedule: 'Transfer schedule',
    transferScheduleSubtitle: 'Assign driver and vehicle with conflict checks',
    createTransfer: 'Add transfer',
    clientName: 'Client',
    routeFrom: 'From',
    routeTo: 'To',
    startTime: 'Start time',
    endTime: 'End time',
    assignedDriver: 'Driver',
    vehicle: 'Vehicle',
    conflictDetected: 'Conflict: the driver or vehicle is already booked for this slot',
    invalidTimeRange: 'End time must be after start time',
    transferSaved: 'Transfer saved to schedule',
    noTransfers: 'No scheduled transfers',
    myTransfers: 'My transfers',
    noTransfersForRole: 'No transfers assigned yet',
    filters: 'Filters',
    filterDate: 'Date',
    filterDriver: 'Driver',
    filterVehicle: 'Vehicle',
    searchTransfers: 'Search by client/route',
    clearFilters: 'Clear filters',
    bufferLabel: 'Buffer (min) for conflict check',
    bufferHelper: 'Adds slack to start/end time for driver and vehicle',
    exportJson: 'Export JSON',
    importJson: 'Import JSON',
    printSchedule: 'Print / PDF',
    importSuccess: 'Import completed',
    importError: 'Import error: invalid file',
    notifyLabel: 'Booking notifications',
    notifyEnable: 'Enable browser notifications to stay updated',
    notifyEnabled: 'Notifications are on',
    notifyBlocked: 'Notifications are blocked. Check browser settings',
    notifyButton: 'Enable notifications',
    notifyTitle: 'Request sent',
    notifyBody: 'We will get back to confirm your booking',
    supportCardTitle: 'Reach a manager',
    supportCall: 'Call',
    supportEmail: 'Email',
    supportWhatsapp: 'Open WhatsApp',
    preferredContactTitle: 'Preferred contact',
    preferCall: 'Call',
    preferWhatsapp: 'WhatsApp',
    primaryCtaCall: 'Call now',
    receiptEmailButton: 'Email receipt',
    receiptPdfButton: 'Download PDF',
    receiptPrompt: 'Enter email for receipt',
    receiptInvalid: 'Enter a valid email address',
    receiptOpened: 'Receipt email draft was opened',
    receiptPdfReady: 'PDF receipt is downloading',
    receiptPdfFailed: 'Could not generate PDF receipt',
    lastOrderTitle: 'Last request',
    lastOrderEmpty: 'No requests yet',
    statusTimeline: 'Steps',
    staffLoginPlaceholder: 'admin or driver@mail.ru',
    staffLoginHint: 'Staff access is available only inside a secured backend environment.',
    transferSearchPlaceholder: 'Name, address, route',
    clientNamePlaceholder: 'Client name',
    routeFromPlaceholder: 'Astana airport',
    routeToPlaceholder: 'Hotel',
    driverLoginPlaceholder: 'driver@mail.ru',
    vehiclePlaceholder: 'Mercedes V-class',
    detectLocation: 'Detect my location',
    locating: 'Detecting location...',
    locationSuccess: 'Address was added to the form',
    locationDenied: 'Location access was denied',
    locationUnavailable: 'Geolocation is not available in this browser',
    locationFailed: 'Could not resolve address, check internet or permission',
    voiceInputAddress: 'Speak address',
    voiceInputListening: 'Listening...',
    voiceInputUnsupported: 'Voice input is not available in this browser',
    voiceInputNoSpeech: 'No speech detected, try again',
    voiceInputApplied: 'Address was added by voice',
    trustNoHiddenFees: 'No hidden fees',
    trustNda: 'Trip and route confidentiality',
    trustInsured: 'Passenger and liability insurance',
    privacyConsentLabel: 'I agree to personal data processing for booking purposes',
    privacyPolicyLabel: 'Privacy Policy',
    termsLabel: 'Terms of Service',
    rememberDataLabel: 'Remember data on this device',
    rememberDataHint: 'If disabled, data is saved only for the current browser session',
    clearMyData: 'Delete my data from this device',
    dataCleared: 'Local data deleted',
    submitConsentRequired: 'Please confirm consent to data processing',
    waIncludeSensitive: 'Include address and comment in WhatsApp',
    waPrivacyHint: 'Only essential details are sent to WhatsApp by default. Address and comment are optional.',
    staffLoginDisabled: 'Staff login is available only in a secured backend environment. Demo login is disabled.',
    waComment: 'Comment',
    legalDisclaimer: 'Service is provided under contract and privacy policy compliance.',
    priceFromTrip: 'from 10,000 KZT per trip',
    moreItems: 'more',
    callAriaLabel: 'Call',
    bottomBrand: 'MAX · Taxi Park',
    orderNowCta: 'Book now ->',
    offlineDemo: 'Offline demo',
    deleteTransferAria: 'Delete transfer',
    footerTagline: 'MAX taxi park in Astana: taxi and transfers',
    favNoteEdit: 'Note',
    favNotePlaceholder: 'E.g.: parking on the left',
    reactivationTitle: "Haven't ordered in a while?",
    reactivationHint: 'Come back and get 5% off your next trip with promo code',
    reactivationCode: 'WELCOME5',
    reactivationDismiss: 'Not now',
    reactivationOrder: 'Book with discount',
    historyAutoCleanedNotice: 'Old orders (>90 days) were auto-removed for your privacy.',
    fleetTitle: 'Our Fleet',
    corporateTitle: 'MAX for Business',
    corpSubtitle: 'Corporate Services',
    corpP1: 'We provide premium transportation solutions for companies. Enjoy dedicated account managers, transparent billing, and top-tier service tailored perfectly to your corporate needs.',
    corpBen1: 'Invoices & Receipts',
    corpBen2: '24/7 Dedicated Manager',
    corpBen3: 'Post-payment basis',
    faqTitle: 'Frequently Asked Questions',
  },
}

export const serviceCatalog = [
  {
    icon: Plane,
    title: {
      ru: 'Аэропорт и вокзал',
      kk: 'Әуежай және вокзал',
      en: 'Airport and train station',
    },
    subtitle: {
      ru: 'Трансфер в аэропорт и из аэропорта',
      kk: 'Әуежайға және әуежайдан трансфер',
      en: 'Airport transfer to and from the terminal',
    },
    price: {
      ru: 'от 15 000 ₸',
      kk: '15 000 ₸ бастап',
      en: 'from 15,000 KZT',
    },
    details: {
      ru: [
        'Подача автомобиля в удобное время',
        'Помощь с багажом и парковкой',
        'До 60 мин ожидания при задержке рейса',
        'Чистый салон и комфортный маршрут',
        'Поддержка по WhatsApp и телефону',
      ],
      kk: [
        'Көлікті ыңғайлы уақытта жеткізу',
        'Жүкпен және паркингпен көмек',
        'Рейс кешіксе 60 минутқа дейін күту',
        'Таза салон және ыңғайлы маршрут',
        'WhatsApp және телефон арқылы қолдау',
      ],
      en: [
        'Vehicle pickup at a convenient time',
        'Assistance with luggage and parking',
        'Up to 60 minutes waiting for delayed flights',
        'Clean cabin and comfortable route',
        'Support by WhatsApp and phone',
      ],
    },
  },
  {
    icon: Baby,
    title: {
      ru: 'Семейные и детские поездки',
      kk: 'Отбасылық және балалық сапарлар',
      en: 'Family and kids rides',
    },
    subtitle: {
      ru: 'Школьный и детский трансфер',
      kk: 'Мектеп және балалар трансфері',
      en: 'School and kids transfer',
    },
    price: {
      ru: 'от 100 000 ₸ / мес',
      kk: '100 000 ₸ / ай бастап',
      en: 'from 100,000 KZT / month',
    },
    details: {
      ru: [
        'Поездки от двери до двери',
        'Надежный водитель и чистый салон',
        'Регулярные маршруты по утрам и вечерам',
        'Поддержка по расписанию и по запросу',
      ],
      kk: [
        'Есіктен есікке дейін сапар',
        'Сенімді жүргізуші және таза салон',
        'Таңертеңгі және кешкі тұрақты бағыттар',
        'Кесте бойынша және сұраныс бойынша қолдау',
      ],
      en: [
        'Door-to-door rides',
        'Reliable driver and clean cabin',
        'Regular morning and evening routes',
        'Scheduled or on-demand support',
      ],
    },
  },
  {
    icon: BriefcaseBusiness,
    title: {
      ru: 'Корпоративное такси',
      kk: 'Корпоративтік такси',
      en: 'Corporate taxi',
    },
    subtitle: {
      ru: 'Поездки для бизнеса',
      kk: 'Бизнес үшін сапарлар',
      en: 'Business rides',
    },
    price: {
      ru: 'от 10 000 ₸ / час',
      kk: '10 000 ₸ / сағ бастап',
      en: 'from 10,000 KZT / hour',
    },
    details: {
      ru: [
        'Поездки для сотрудников, встреч и переговоров',
        'Пунктуальность и порядок маршрутов',
        'Поддержка в любое время дня и ночи',
        'Подбор автомобиля под задачу',
      ],
      kk: [
        'Қызметкерлер, кездесулер және келіссөздер сапарлары',
        'Уақыттылық және маршрут тәртібі',
        'Түнгі де күндізгі де қолдау',
        'Міндетке сәйкес көлік таңдау',
      ],
      en: [
        'Trips for staff, meetings, and negotiations',
        'Punctuality and clear routing',
        'Support day and night',
        'Vehicle selection based on your task',
      ],
    },
  },
  {
    icon: Building2,
    title: {
      ru: 'Корпоративный парк',
      kk: 'Корпоративтік парк',
      en: 'Corporate fleet',
    },
    subtitle: {
      ru: 'Регулярные поездки для компаний',
      kk: 'Компаниялар үшін тұрақты сапарлар',
      en: 'Regular trips for companies',
    },
    price: {
      ru: 'Индивидуальный тариф',
      kk: 'Жеке тариф',
      en: 'Custom pricing',
    },
    details: {
      ru: [
        'Бронируйте поездки заранее и без лишней суеты',
        'Поддержка для бухгалтерии и менеджеров',
        'Подмена автомобиля при необходимости',
        'Персональный менеджер 24/7',
      ],
      kk: [
        'Сапарларды алдын ала брондай аласыз',
        'Бухгалтерия мен менеджерлерге қолдау',
        'Қажет болған кезде көлікті ауыстыру',
        '24/7 жеке менеджер',
      ],
      en: [
        'Book rides in advance without extra hassle',
        'Support for finance and management teams',
        'Vehicle replacement when needed',
        'Dedicated manager available 24/7',
      ],
    },
  },
  {
    icon: MapPin,
    title: {
      ru: 'Межгород и поездки по области',
      kk: 'Қалааралық және ауданаралық сапарлар',
      en: 'Intercity and regional rides',
    },
    subtitle: {
      ru: 'Комфортные поездки за город',
      kk: 'Қала сыртындағы ыңғайлы сапарлар',
      en: 'Comfortable rides outside the city',
    },
    price: {
      ru: 'По запросу',
      kk: 'Сұраныс бойынша',
      en: 'On request',
    },
    details: {
      ru: [
        'Маршруты по области и в популярные курортные точки',
        'Надежный водитель и спокойная дорога',
        'Остановки по желанию',
        'Подготовка машины перед выездом',
      ],
      kk: [
        'Аудан және танымал курорт нүктелеріне бағыттар',
        'Сенімді жүргізуші және тыныш жол',
        'Қалауы бойынша аялдамалар',
        'Сапар алдында көлікті дайындау',
      ],
      en: [
        'Routes across the region and to popular resort areas',
        'Reliable driver and calm road experience',
        'Stops on request',
        'Vehicle preparation before departure',
      ],
    },
  },
  {
    icon: HelpCircle,
    title: {
      ru: 'Другое',
      kk: 'Басқа қызметтер',
      en: 'Other Requests',
    },
    subtitle: {
      ru: 'Индивидуальные решения',
      kk: 'Жеке шешімдер',
      en: 'Custom Services',
    },
    price: {
      ru: 'Уточняйте',
      kk: 'Нақтылаңыз',
      en: 'Ask for quote',
    },
    details: {
      ru: [
        'Вам нужен нестандартный сервис?',
        'Специальные требования к маршруту?',
        'Особые пожелания к авто или водителю?',
        'Свяжитесь с нами напрямую в WhatsApp',
        'Мы найдем идеальное решение для вас',
      ],
      kk: [
        'Стандарттан тыс қызмет керек пе?',
        'Маршрутқа арнайы талаптарыңыз бар ма?',
        'Көлікке немесе жүргізушіге ерекше тілек бар ма?',
        'WhatsApp арқылы тікелей бізге жазыңыз',
        'Сізге ең тиімді шешімді ұсынамыз',
      ],
      en: [
        'Need a non-standard service?',
        'Special route requirements?',
        'Specific requests for vehicle or driver?',
        'Contact us directly on WhatsApp',
        'We will tailor the best solution for you',
      ],
    },
  },
]

export const getServices = (language) => serviceCatalog.map((service) => ({
  icon: service.icon,
  title: service.title[language],
  subtitle: service.subtitle[language],
  price: service.price[language],
  details: service.details[language],
}))

export const getStandards = (language) => {
  const standardsByLanguage = {
    ru: [
      { title: 'Идеальная чистота', icon: Sparkles, desc: 'Автомобиль подается после комплексной мойки и химчистки салона.' },
      { title: 'Дресс-код и этикет', icon: Crown, desc: 'Водители в строгих костюмах, соблюдение протокола тишины и профессиональная вежливость.' },
      { title: 'Напитки на борту', icon: Droplets, desc: 'Свежая питьевая вода в каждой поездке.' },
      { title: 'Энергия для гаджетов', icon: Battery, desc: 'Зарядные устройства для всех типов смартфонов (Type-C, Lightning).' },
      { title: 'Опытные водители', icon: UserCheck, desc: 'Профессиональный и безаварийный многолетний стаж.' },
      { title: 'Полная страховка', icon: Award, desc: 'Страховое покрытие пассажира, водителя и автомобиля.' },
    ],
    kk: [
      { title: 'Мінсіз тазалық', icon: Sparkles, desc: 'Көлік кешенді жуу және салонды химиялық тазалаудан кейін беріледі.' },
      { title: 'Дресс-код және этикет', icon: Crown, desc: 'Жүргізушілер қатаң костюммен, тыныштық протоколын және кәсіби сыпайылықты сақтайды.' },
      { title: 'Жолдағы сусындар', icon: Droplets, desc: 'Әр сапарда таза ауыз су ұсынылады.' },
      { title: 'Гаджеттерге қуат', icon: Battery, desc: 'Смартфондардың барлық түріне арналған қуаттағыштар (Type-C, Lightning).' },
      { title: 'Тәжірибелі жүргізушілер', icon: UserCheck, desc: 'Көпжылдық тәжірибесі бар кәсіби және апатсыз жүргізушілер.' },
      { title: 'Толық сақтандыру', icon: Award, desc: 'Жолаушы, жүргізуші және көлік толық сақтандырылған.' },
    ],
    en: [
      { title: 'Spotless Cleanliness', icon: Sparkles, desc: 'Each vehicle is delivered after a full exterior wash and interior detailing.' },
      { title: 'Dress Code & Etiquette', icon: Crown, desc: 'Drivers wear formal suits, follow silence protocol, and maintain professional courtesy.' },
      { title: 'On-Board Refreshments', icon: Droplets, desc: 'Fresh drinking water is provided on every trip.' },
      { title: 'Power for Devices', icon: Battery, desc: 'Charging cables for all major smartphone types (Type-C, Lightning).' },
      { title: 'Experienced Drivers', icon: UserCheck, desc: 'Professional, safety-focused drivers with long-term experience.' },
      { title: 'Full Insurance', icon: Award, desc: 'Comprehensive coverage for passenger, driver, and vehicle.' },
    ],
  }

  return standardsByLanguage[language] || standardsByLanguage.ru
}

export const getQuickScenarios = (language) => {
  const services = getServices(language)
  const quickScenariosByLanguage = {
    ru: [
      { label: 'Аэропорт', serviceIndex: 0, address: 'Аэропорт Астана' },
      { label: 'Детский маршрут', serviceIndex: 1, address: 'Школа / дом' },
      { label: 'Бизнес-день', serviceIndex: 2, address: 'Офис / встречи' },
    ],
    kk: [
      { label: 'Әуежай', serviceIndex: 0, address: 'Астана әуежайы' },
      { label: 'Балалар маршруты', serviceIndex: 1, address: 'Мектеп / үй' },
      { label: 'Бизнес-күн', serviceIndex: 2, address: 'Кеңсе / кездесулер' },
    ],
    en: [
      { label: 'Airport', serviceIndex: 0, address: 'Astana Airport' },
      { label: 'Kids Route', serviceIndex: 1, address: 'School / home' },
      { label: 'Business Day', serviceIndex: 2, address: 'Office / meetings' },
    ],
  }

  return (quickScenariosByLanguage[language] || quickScenariosByLanguage.ru).map((scenario) => ({
    ...scenario,
    service: services[scenario.serviceIndex]?.title || services[0]?.title || '',
  }))
}

export const getReviews = (language) => {
  const reviewsByLanguage = {
    ru: [
      {
        author: 'Алия К.',
        text: 'Всегда вовремя, салон чистый, водитель вежливый. Для аэропорта - лучший вариант.',
      },
      {
        author: 'N. Consulting',
        text: 'Используем для корпоративных гостей. Сервис стабильный, отчетность и коммуникация на уровне.',
      },
      {
        author: 'Руслан М.',
        text: 'Быстро подтвердили заказ в WhatsApp и сразу закрыли вопрос с маршрутом.',
      },
    ],
    kk: [
      {
        author: 'Алия К.',
        text: 'Әрдайым уақытында келеді, салон таза, жүргізуші сыпайы. Әуежайға өте ыңғайлы.',
      },
      {
        author: 'N. Consulting',
        text: 'Корпоративтік қонақтар үшін қолданамыз. Сервис тұрақты, есеп пен байланыс жоғары деңгейде.',
      },
      {
        author: 'Руслан М.',
        text: 'WhatsApp арқылы тапсырысты тез растады және маршрутты бірден шешті.',
      },
    ],
    en: [
      {
        author: 'Aliya K.',
        text: 'Always on time, clean cabin, polite driver. Best option for airport rides.',
      },
      {
        author: 'N. Consulting',
        text: 'We use MAX for corporate guests. Reliable service and excellent communication.',
      },
      {
        author: 'Ruslan M.',
        text: 'They confirmed my WhatsApp booking quickly and handled route details right away.',
      },
    ],
  }

  return reviewsByLanguage[language] || reviewsByLanguage.ru
}

export const getFleet = (language) => {
  const fleetByLanguage = {
    ru: [
      { class: 'Комфорт+', models: 'Toyota Camry 70/75', desc: 'Идеально для ежедневных поездок и трансферов. Просторный салон, климат-контроль.', price: 'от 2000 ₸', icon: 'Car' },
      { class: 'Бизнес & VIP', models: 'Mercedes S-class (W222, W223)', desc: 'Для корпоративных клиентов и важных встреч. Кожаный салон, тишина, вода.', price: 'от 5000 ₸', icon: 'Crown' },
      { class: 'Минивен', models: 'Mercedes-Benz V-class', desc: 'Для поездок группой до 7 человек. Удобные кресла, много места для багажа.', price: 'от 8000 ₸', icon: 'BriefcaseBusiness' }
    ],
    kk: [
      { class: 'Жайлылық+', models: 'Toyota Camry 70/75', desc: 'Күнделікті сапарлар үшін тамаша. Кең салон, климат-бақылау.', price: '2000 ₸ бастап', icon: 'Car' },
      { class: 'Бизнес & VIP', models: 'Mercedes S-class (W222, W223)', desc: 'Корпоративтік қонақтар үшін. Былғары салон, тыныштық, су.', price: '5000 ₸ бастап', icon: 'Crown' },
      { class: 'Минивен', models: 'Mercedes-Benz V-class', desc: '7 адамға дейін топтық сапарлар үшін. Көп жүк орны.', price: '8000 ₸ бастап', icon: 'BriefcaseBusiness' }
    ],
    en: [
      { class: 'Comfort+', models: 'Toyota Camry 70/75', desc: 'Perfect for daily trips. Spacious interior, climate control.', price: 'from 2000 ₸', icon: 'Car' },
      { class: 'Business & VIP', models: 'Mercedes S-class (W222, W223)', desc: 'For corporate clients. Leather interior, quietness, water.', price: 'from 5000 ₸', icon: 'Crown' },
      { class: 'Minivan', models: 'Mercedes-Benz V-class', desc: 'For group trips up to 7 people. Lots of luggage space.', price: 'from 8000 ₸', icon: 'BriefcaseBusiness' }
    ]
  }
  return fleetByLanguage[language] || fleetByLanguage.ru;
}

export const getFaq = (language) => {
  const faqByLanguage = {
    ru: [
      { q: 'Как быстро подается машина?', a: 'Среднее время подачи авто — от 5 до 15 минут в зависимости от района города и класса автомобиля.' },
      { q: 'Могу ли я оплатить безналичным расчетом?', a: 'Да, для корпоративных клиентов доступна оплата по счёту. Для физических лиц — переводы Kaspi/Halyk, а также Apple Pay через терминал в машинах бизнес-класса.' },
      { q: 'Встречаете ли вы с табличкой в аэропорту?', a: 'Конечно. Водитель встретит вас в зоне прилета или выдачи багажа с именной табличкой, поможет с багажом и проводит к автомобилю.' },
      { q: 'Предоставляете ли вы отчетные документы?', a: 'Да, мы выдаем электронные фискальные чеки, а также счета-фактуры (ЭСФ) и акты выполненных работ для юридических лиц через ИС ЭСФ.' },
      { q: 'Можно ли заказать микроавтобус для группы?', a: 'Да, в нашем автопарке есть комфортабельные минивэны Mercedes-Benz V-class (до 7 мест) и Sprinter для больших делегаций.' },
      { q: 'Есть ли детские кресла?', a: 'Да, при заказе просто укажите, что с вами едет ребёнок и его возраст (или вес). Мы бесплатно предоставим автокресло или бустер.' },
      { q: 'Автомобили ездят только по Астане?', a: 'Нет, мы также осуществляем междугородние трансферы на автомобилях комфорт и бизнес-класса (Алматы, Караганда, Кокшетау, Щучинск/Боровое и другие направления).' },
      { q: 'Могу ли я заключить договор на корпоративное обслуживание?', a: 'Да, мы работаем по договорам. Предоставляем персонального менеджера, постоплату в конце месяца и детализированную отчетность по каждой поездке.' },
      { q: 'Можно ли заранее забронировать машину на определенное время?', a: 'Конечно. Рекомендуем делать предварительный заказ за 2-3 часа или за сутки для трансферов в аэропорт или вокзал. Машина будет подана точно в срок.' },
      { q: 'Соблюдается ли конфиденциальность поездок?', a: 'Абсолютно. В бизнес и VIP-сегменте действует протокол NDA. Наши водители не задают лишних вопросов и гарантируют информационную тишину.' }
    ],
    kk: [
      { q: 'Көлік қанша уақытта келеді?', a: 'Көлік берудің орташа уақыты — қала ауданы мен көлік класына байланысты 5-тен 15 минутқа дейін.' },
      { q: 'Қолма-қол ақшасыз төлей аламын ба?', a: 'Иә, корпоративтік тұтынушылар үшін шот арқылы төлеуге болады. Жеке тұлғалар үшін — Kaspi, Halyk немесе Apple Pay.' },
      { q: 'Әуежайда тақтайшамен қарсы аласыз ба?', a: 'Әрине. Жүргізуші сізді ұшып келу аймағында атаулы тақтайшамен күтіп алады және жүгіңізге көмектеседі.' },
      { q: 'Есеп құжаттарын бересіз бе?', a: 'Иә, біз заңды тұлғалар үшін электронды фискалдық чектер мен ЭШФ (электронды шот-фактура) береміз.' },
      { q: 'Топқа арналған шағын автобус қарай аламын ба?', a: 'Иә, біздің паркте 7 орындық Mercedes-Benz V-class минивэндері бар.' },
      { q: 'Балалар орындығы бар ма?', a: 'Иә, тапсырыс кезінде баланың жасын көрсетсеңіз, біз тегін автокресло береміз.' },
      { q: 'Тек Астана ішінде ғана ма?', a: 'Жоқ, біз қалааралық сапарларды да орындаймыз (Қарағанды, Көкшетау, Бурабай және т.б.).' },
      { q: 'Корпоративтік қызметке келісімшарт жасай аламын ба?', a: 'Иә, біз компаниялармен жұмыс істейміз, жеке менеджер және ай соңында төлеу мүмкіндігі бар.' },
      { q: 'Алдын ала тапсырыс беруге бола ма?', a: 'Әрине, әуежайға немесе вокзалға 2-3 сағат бұрын тапсырыс берген жөн. Көлік дәл уақытында келеді.' },
      { q: 'Құпиялылық сақтала ма?', a: 'Иә, VIP-сегмент үшін NDA хаттамасы жұмыс істейді. Жүргізушілер артық сұрақ қоймайды.' }
    ],
    en: [
      { q: 'How fast does the car arrive?', a: 'Average arrival time is between 5 to 15 minutes depending on the city area and car class.' },
      { q: 'Can I pay by card/bank transfer?', a: 'Yes, corporate clients can pay via invoice. Individuals can use Kaspi, Halyk, or direct card terminals in business class cars.' },
      { q: 'Do you meet with a name sign at the airport?', a: 'Absolutely. The driver will meet you in the arrivals area with a name sign and help with your luggage.' },
      { q: 'Do you provide invoices and receipts?', a: 'Yes, we provide electronic fiscal receipts and official invoices (ESF) for businesses.' },
      { q: 'Can I book a minivan for a group?', a: 'Yes, we have comfortable Mercedes-Benz V-class minivans (up to 7 seats) for groups.' },
      { q: 'Do you have child seats?', a: 'Yes, please mention the child\'s age/weight when booking, and we will provide a child seat for free.' },
      { q: 'Do you drive only within Astana?', a: 'No, we also provide intercity transfers (Karaganda, Borovoe, Almaty, etc.) in comfort and business class cars.' },
      { q: 'Can we sign a corporate agreement?', a: 'Yes, we provide B2B services with a personal manager, post-payment options, and detailed reports.' },
      { q: 'Can I book a car in advance?', a: 'Yes, we recommend booking 2-3 hours in advance for airport or railway station transfers.' },
      { q: 'Is my trip confidential?', a: 'Absolutely. We apply NDA protocols for business and VIP clients. Strict privacy is guaranteed.' }
    ]
  }
  return faqByLanguage[language] || faqByLanguage.ru;
}
